name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: 2.9.0 
  permission_handler: ^10.2.0
  geolocator: ^8.2.0
  google_sign_in: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  supabase_flutter: ^0.2.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png" # Caminho para o seu ícone

flutter:
  uses-material-design: true

  assets:
    - assets/tela.jpg
